r"""Production nonlinear finite-cylinder integrator for ``(u_1, omega_1, psi_1)``.

The audited system (``docs/equation_audit.md``, E-11--E-14) is

.. math::

   \partial_t u_1 + u^r u_{1,r} + u^z u_{1,z}
       &= 2 u_1 \psi_{1,z} + \nu \mathcal L_5 u_1 + F_{u_1},\\
   \partial_t \omega_1 + u^r \omega_{1,r} + u^z \omega_{1,z}
       &= \partial_z(u_1^2) + \nu \mathcal L_5 \omega_1 + F_{\omega_1},\\
   -\mathcal L_5 \psi_1 &= \omega_1,\qquad
   \mathcal L_5 = \partial_{rr} + \tfrac{3}{r}\partial_r + \partial_{zz},\\
   u^r &= -r\psi_{1,z},\qquad u^z = 2\psi_1 + r\psi_{1,r}.

The geometry is the Hou finite cylinder: ``0 <= r <= r_max`` (production
``r_max = 1``), full period in ``z``, wall conditions E-27 at ``r = r_max``.
``F_{u_1}`` and ``F_{\omega_1}`` are manufactured forcings used only by the
verification tests; production runs use ``None``.

Stage ordering (identical in every Heun stage; ``n_r-1`` is the wall row)
--------------------------------------------------------------------------

Every state pair ``(u_1, \omega_1)`` produced by an update is immediately
mapped to a *constrained* state by :func:`constrain_state`, in this order:

1. ``u_1[n_r-1, :] = 0``                       (E-27 no-slip swirl trace).
2. ``psi_1 = solve_streamfunction_poisson(omega_1, g = 0)``   (E-13 with the
   single Dirichlet condition ``psi_1(r_max, z) = 0`` of E-27; imposing
   ``psi_{1,r} = 0`` as well would over-determine the elliptic problem).
3. ``omega_1[n_r-1, :] = -(8 psi_1[n_r-2, :] - psi_1[n_r-3, :])/(2 dr^2)``
   (E-31, second-order Thom-type wall vorticity).
4. ``u^r, u^z`` are recovered from ``psi_1`` by E-14.

Step 2 precedes step 3, and that ordering is *exact* rather than a lagged
approximation: solver A eliminates the outer Dirichlet unknown and builds its
right-hand side from radial rows ``0 .. n_r-2`` only, so the wall row of
``omega_1`` never enters the elliptic solve.  Re-solving after step 3 would
return the identical ``psi_1``; the constrained state is a fixed point of the
map.

The right-hand side (:func:`right_hand_side`) is evaluated from a constrained
state and its wall rows are set to zero, because both wall rows are algebraic
constraints rather than evolution equations.  Consequently every Heun update
leaves the wall rows untouched and they are regenerated by the next
:func:`constrain_state` call.

Time-step policy and the meaning of the recorded CFL number
------------------------------------------------------------

:func:`adaptive_time_step` evaluates the advective bound

.. math::

   dt \le C \min\!\big(dr/\max|u^r|,\ dz/\max|u^z|\big)

at the **start** of the step, from the state that is about to be advanced.
:func:`compute_diagnostics` instead reports ``advective_cfl`` as
``dt * max(max|u^r|/dr, max|u^z|/dz)`` measured on the state that the step
**produced**.  The two agree exactly when the meridional velocities do not
change during the step, because ``max(u/h)`` is the reciprocal of
``min(h/u)``; the recorded *effective* CFL therefore equals ``C`` times the
one-step relative growth of the dominant directional velocity ratio whenever
the advective bound is the active constraint.  It can consequently exceed
``C`` by exactly that growth factor.  The clipping of ``dt`` to snapshot,
viscosity-switch and ``t_final`` targets and the ``max_time_step`` cap can
only shrink ``dt``, so neither can raise the effective CFL above this bound.
The delegated numerical-method guidance recorded in
``docs/hou_setup_audit.md`` (HH21, arXiv:2102.06663 Appendix A) pairs the
CFL number ``0.1`` with a one-step relative growth of the maximum below one
percent, which bounds the excess.  In the shipped ``outputs/hou_early_time_v1``
run the largest recorded effective CFL was ``0.10022676304450114`` against
``cfl_coefficient = 0.1``, i.e. an excess of ``0.23`` percent (0.0022676),
well inside that one-percent guidance.  The experiment therefore accepts the
effective CFL against ``C * (1 + cfl_excess_tolerance)`` rather than against
``C`` itself; see ``experiments/run_hou_early_time.py``.

Relativized constraint diagnostics (TM-09)
------------------------------------------------------------

``docs/threat_model.md`` TM-09 warns that a small residual computed as the
difference of large terms says nothing on its own.  :func:`compute_diagnostics`
therefore reports the E-02 divergence residual and the E-16c axis parity defect
*both* absolutely and divided by their own cancellation scales
(:func:`relative_divergence`, :func:`relative_axis_parity`), together with the
denominators themselves and the grid locations of the maxima.  These relative
numbers are recorded, not gated.

Recorded deviations from ``docs/nonlinear_solver_design.md``
------------------------------------------------------------

* :func:`adaptive_time_step` accepts an optional ``max_time_step`` cap that the
  design does not list.  It is required because the design rule alone returns
  the viscous bound ``C min(dr,dz)^2/(4 nu)`` whenever the meridional velocity
  vanishes, and the E-29 initial datum has ``u^r = u^z = 0`` exactly; on a
  ``129 x 256`` grid with ``nu = 5e-4`` that first step is ``7.6e-4``, roughly a
  third of the whole early-time target window.  The cap is optional, defaults to
  absent, and never enlarges a step.
* The design's fault list includes "ignore the viscosity switch"; that path is
  covered here by direct assertions on :func:`viscosity_at` and on the switch
  times recorded by :func:`integrate` rather than by an injected fault.

The ``fault`` arguments exist only so that rejection tests can prove the
acceptance criteria are able to fail.  Production runs must pass ``None``.

Nothing in this module is a proof, an interval enclosure, or evidence for
singularity formation.  It is a floating-point candidate generator whose
snapshots are meant to be re-examined by the independent verification path
(solver B in :mod:`ns_certificate_lab.finite_cylinder_poisson`,
:mod:`ns_certificate_lab.pde` residuals, the Cartesian adapter).
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from pathlib import Path
from typing import Any, Callable, Literal, Mapping, Sequence

import numpy as np
import numpy.typing as npt

from .artifacts import CandidatePaths, load_candidate, save_candidate
from .grid import AxisymmetricGrid, FloatArray
from .operators import (
    derivative_r,
    derivative_z,
    divergence_physical,
    divergence_terms,
    laplacian_5d_formal,
    recover_velocity,
)
from .poisson import solve_streamfunction_poisson

Forcing = Callable[[float], npt.ArrayLike] | None

Fault = Literal[
    "thom_sign",
    "stretch_sign",
    "axis_coeff",
    "wall_leak",
    "poisson_sign",
]
VALID_FAULTS: tuple[Fault, ...] = (
    "thom_sign",
    "stretch_sign",
    "axis_coeff",
    "wall_leak",
    "poisson_sign",
)

FAULT_DESCRIPTIONS: dict[str, str] = {
    "thom_sign": "flip the sign of the E-31 wall vorticity reconstruction",
    "stretch_sign": "flip the sign of the +2 u1 psi1_z stretching term (E-11)",
    "axis_coeff": (
        "replace the axis radial coefficient 8 of the discrete L5 by 4 "
        "(E-17 violated on the axis row only)"
    ),
    "wall_leak": (
        "skip all wall-row reconstruction: u1(r_max,z) is not pinned to zero "
        "and omega1(r_max,z) is not regenerated from E-31, so both wall rows "
        "stay frozen at their initial values"
    ),
    "poisson_sign": "flip the sign of the elliptic solution psi1 (E-13)",
}

_TIME_TOLERANCE = 1.0e-12
_VELOCITY_FLOOR = 1.0e-12
# Guard for relative diagnostics.  It is far below any physically meaningful
# scale, so it only removes the 0/0 case and never rescales a real ratio.
_DENOMINATOR_FLOOR = 1.0e-300


def _check_fault(fault: Fault | None) -> None:
    if fault is not None and fault not in VALID_FAULTS:
        raise ValueError(f"unknown injected fault: {fault!r}")


@dataclass(frozen=True)
class ConstrainedState:
    """A state that already satisfies the algebraic wall constraints.

    ``psi1`` is the elliptic solution of ``omega1`` and ``u_r``/``u_z`` are the
    E-14 velocities recovered from it.  Instances are produced only by
    :func:`constrain_state` so that no unconstrained state can reach the
    right-hand side.
    """

    u1: FloatArray
    omega1: FloatArray
    psi1: FloatArray
    u_r: FloatArray
    u_z: FloatArray


def solve_poisson(
    grid: AxisymmetricGrid,
    omega1: npt.ArrayLike,
    *,
    outer_dirichlet: npt.ArrayLike | None = None,
) -> FloatArray:
    """Solve ``-L5 psi1 = omega1`` with the homogeneous wall trace of E-27.

    ``outer_dirichlet`` exists for manufactured tests on domains where the
    wall trace is not zero; production Hou runs always use ``g = 0``.
    """

    trace = (
        np.zeros(grid.nz, dtype=np.float64)
        if outer_dirichlet is None
        else np.asarray(outer_dirichlet, dtype=np.float64)
    )
    solution = solve_streamfunction_poisson(
        grid,
        omega1,
        trace,
        estimate_condition=False,
    )
    return solution.psi1


def thom_wall_vorticity(
    grid: AxisymmetricGrid,
    psi1: npt.ArrayLike,
    *,
    fault: Fault | None = None,
) -> FloatArray:
    """Return the E-31 second-order wall vorticity trace ``omega1(r_max, z)``.

    ``omega1(1,z) = -(8 psi1[n-1] - psi1[n-2]) / (2 dr^2) + O(dr^2)`` follows
    from ``psi1(1,z) = psi1_r(1,z) = 0`` by eliminating ``psi1_rrr``.
    """

    _check_fault(fault)
    psi = grid.validate_field(psi1, name="psi1")
    trace = -(8.0 * psi[-2] - psi[-3]) / (2.0 * grid.dr**2)
    if fault == "thom_sign":
        trace = -trace
    return np.asarray(trace, dtype=np.float64)


def constrain_state(
    grid: AxisymmetricGrid,
    u1: npt.ArrayLike,
    omega1: npt.ArrayLike,
    *,
    fault: Fault | None = None,
    outer_dirichlet: npt.ArrayLike | None = None,
) -> ConstrainedState:
    """Apply the wall constraints and the elliptic solve in the documented order."""

    _check_fault(fault)
    swirl = grid.validate_field(u1, name="u1").copy()
    vorticity = grid.validate_field(omega1, name="omega1").copy()
    if fault != "wall_leak":
        swirl[-1] = 0.0
    psi1 = solve_poisson(grid, vorticity, outer_dirichlet=outer_dirichlet)
    if fault == "poisson_sign":
        psi1 = -psi1
    if fault != "wall_leak":
        vorticity[-1] = thom_wall_vorticity(grid, psi1, fault=fault)
    u_r, u_z = recover_velocity(grid, psi1)
    return ConstrainedState(
        u1=swirl,
        omega1=vorticity,
        psi1=psi1,
        u_r=u_r,
        u_z=u_z,
    )


def _viscous_operator(
    grid: AxisymmetricGrid,
    field: FloatArray,
    *,
    fault: Fault | None,
) -> FloatArray:
    """Return the discrete ``L5`` with the optional corrupted axis coefficient."""

    result = laplacian_5d_formal(grid, field)
    if fault == "axis_coeff":
        # The correct axis row is 8 (f1 - f0)/dr^2 (E-17).  Using 4 instead
        # halves that coefficient.
        result[0] -= 4.0 * (field[1] - field[0]) / grid.dr**2
    return result


def _forcing_values(
    grid: AxisymmetricGrid,
    forcing: Forcing,
    time: float,
    *,
    name: str,
) -> FloatArray | None:
    if forcing is None:
        return None
    if not callable(forcing):
        raise TypeError(f"{name} must be callable or None")
    return grid.validate_field(forcing(float(time)), name=name)


def right_hand_side(
    grid: AxisymmetricGrid,
    state: ConstrainedState,
    *,
    viscosity: float,
    time: float = 0.0,
    forcing_u1: Forcing = None,
    forcing_omega1: Forcing = None,
    fault: Fault | None = None,
) -> tuple[FloatArray, FloatArray]:
    """Evaluate E-11 and E-12 on the interior rows of a constrained state."""

    _check_fault(fault)
    if not isinstance(state, ConstrainedState):
        raise TypeError("right_hand_side requires a ConstrainedState")
    nu = float(viscosity)
    if not math.isfinite(nu) or nu < 0.0:
        raise ValueError("viscosity must be finite and nonnegative")

    u1 = state.u1
    omega1 = state.omega1
    u1_r = derivative_r(grid, u1, even_at_axis=True)
    u1_z = derivative_z(grid, u1)
    omega1_r = derivative_r(grid, omega1, even_at_axis=True)
    omega1_z = derivative_z(grid, omega1)
    psi1_z = derivative_z(grid, state.psi1)

    stretching = 2.0 * u1 * psi1_z
    if fault == "stretch_sign":
        stretching = -stretching

    rhs_u1 = (
        -state.u_r * u1_r
        - state.u_z * u1_z
        + stretching
        + nu * _viscous_operator(grid, u1, fault=fault)
    )
    rhs_omega1 = (
        -state.u_r * omega1_r
        - state.u_z * omega1_z
        + derivative_z(grid, u1 * u1)
        + nu * _viscous_operator(grid, omega1, fault=fault)
    )

    force_u1 = _forcing_values(grid, forcing_u1, time, name="forcing_u1")
    if force_u1 is not None:
        rhs_u1 = rhs_u1 + force_u1
    force_omega1 = _forcing_values(grid, forcing_omega1, time, name="forcing_omega1")
    if force_omega1 is not None:
        rhs_omega1 = rhs_omega1 + force_omega1

    # Both wall rows are algebraic constraints, not evolution equations.
    rhs_u1[-1] = 0.0
    rhs_omega1[-1] = 0.0
    if not (np.all(np.isfinite(rhs_u1)) and np.all(np.isfinite(rhs_omega1))):
        raise FloatingPointError("nonlinear cylinder right-hand side became non-finite")
    return rhs_u1, rhs_omega1


def heun_step(
    grid: AxisymmetricGrid,
    state: ConstrainedState,
    *,
    dt: float,
    time: float,
    viscosity: float,
    forcing_u1: Forcing = None,
    forcing_omega1: Forcing = None,
    fault: Fault | None = None,
) -> ConstrainedState:
    """Advance one explicit Heun/RK2 step (``c=(0,1)``, ``a21=1``, ``b=(1/2,1/2)``)."""

    step = float(dt)
    if not math.isfinite(step) or step <= 0.0:
        raise ValueError("dt must be positive and finite")
    k1_u1, k1_omega1 = right_hand_side(
        grid,
        state,
        viscosity=viscosity,
        time=time,
        forcing_u1=forcing_u1,
        forcing_omega1=forcing_omega1,
        fault=fault,
    )
    stage = constrain_state(
        grid,
        state.u1 + step * k1_u1,
        state.omega1 + step * k1_omega1,
        fault=fault,
    )
    k2_u1, k2_omega1 = right_hand_side(
        grid,
        stage,
        viscosity=viscosity,
        time=time + step,
        forcing_u1=forcing_u1,
        forcing_omega1=forcing_omega1,
        fault=fault,
    )
    return constrain_state(
        grid,
        state.u1 + 0.5 * step * (k1_u1 + k2_u1),
        state.omega1 + 0.5 * step * (k1_omega1 + k2_omega1),
        fault=fault,
    )


def adaptive_time_step(
    grid: AxisymmetricGrid,
    state: ConstrainedState,
    *,
    viscosity: float,
    cfl_coefficient: float = 0.1,
    max_time_step: float | None = None,
) -> float:
    """Return the design section 4 adaptive step.

    ``dt = C min(dr/max|u^r|, dz/max|u^z|, min(dr^2,dz^2)/(4 nu))``.  The
    factor four is the axis-limit stability margin of E-17.

    The velocity maxima are those of ``state``, i.e. the step is sized at the
    **start of the step**.  ``compute_diagnostics`` reports ``advective_cfl``
    from the state the step produced, so the two differ by the intra-step
    growth of the velocity maxima:

    * with the advective bound active and frozen velocities the recorded
      effective CFL is exactly ``C``, because
      ``max(u^r/dr, u^z/dz) = 1 / min(dr/u^r, dz/u^z)``;
    * if the dominant ratio ``max(|u^r|/dr, |u^z|/dz)`` grows by a relative
      factor ``g`` during the step, the recorded value is ``C (1 + g)``.  The
      HH21 guidance recorded in ``docs/hou_setup_audit.md`` keeps ``g`` below
      one percent; ``outputs/hou_early_time_v1`` measured ``g = 0.0022676``
      (0.23 percent) at its worst step;
    * when the viscous bound, the ``max_time_step`` cap or the clipping to a
      snapshot / viscosity-switch / ``t_final`` target is the binding
      constraint the step is *smaller* than the advective bound, so the
      recorded effective CFL falls strictly below ``C``.

    None of these paths can push the effective CFL above ``C (1 + g)``, which
    is why the experiment accepts it against a small explicit excess
    tolerance rather than against ``C`` exactly.
    """

    coefficient = float(cfl_coefficient)
    if not math.isfinite(coefficient) or coefficient <= 0.0:
        raise ValueError("cfl_coefficient must be positive and finite")
    nu = float(viscosity)
    if not math.isfinite(nu) or nu <= 0.0:
        raise ValueError("adaptive stepping requires a positive finite viscosity")
    max_u_r = float(np.max(np.abs(state.u_r)))
    max_u_z = float(np.max(np.abs(state.u_z)))
    candidates = [
        coefficient * grid.dr / (max_u_r + _VELOCITY_FLOOR),
        coefficient * grid.dz / (max_u_z + _VELOCITY_FLOOR),
        coefficient * min(grid.dr**2, grid.dz**2) / (4.0 * nu),
    ]
    if max_time_step is not None:
        cap = float(max_time_step)
        if not math.isfinite(cap) or cap <= 0.0:
            raise ValueError("max_time_step must be positive and finite")
        candidates.append(cap)
    return min(candidates)


def normalize_viscosity_schedule(
    schedule: Sequence[Sequence[float]],
) -> tuple[tuple[float, float], ...]:
    """Validate a piecewise-constant ``[[t_switch, nu], ...]`` schedule (E-30)."""

    if not isinstance(schedule, Sequence) or isinstance(schedule, (str, bytes)):
        raise ValueError("viscosity_schedule must be a sequence of pairs")
    entries: list[tuple[float, float]] = []
    for item in schedule:
        if (
            not isinstance(item, Sequence)
            or isinstance(item, (str, bytes))
            or len(item) != 2
        ):
            raise ValueError("viscosity_schedule entries must be [time, viscosity]")
        raw_time, raw_nu = item
        if isinstance(raw_time, bool) or isinstance(raw_nu, bool):
            raise ValueError("viscosity_schedule entries must be numbers")
        switch_time = float(raw_time)
        nu = float(raw_nu)
        if not math.isfinite(switch_time) or switch_time < 0.0:
            raise ValueError("viscosity switch times must be finite and nonnegative")
        if not math.isfinite(nu) or nu <= 0.0:
            raise ValueError("viscosity values must be finite and positive")
        entries.append((switch_time, nu))
    if not entries:
        raise ValueError("viscosity_schedule must contain at least one entry")
    if entries[0][0] != 0.0:
        raise ValueError("the first viscosity switch time must be exactly zero")
    if any(a[0] >= b[0] for a, b in zip(entries, entries[1:])):
        raise ValueError("viscosity switch times must be strictly increasing")
    return tuple(entries)


def viscosity_at(
    schedule: Sequence[Sequence[float]],
    time: float,
) -> float:
    """Return the piecewise-constant viscosity in force at ``time``."""

    entries = normalize_viscosity_schedule(schedule)
    value = entries[0][1]
    for switch_time, nu in entries:
        if time >= switch_time - _TIME_TOLERANCE:
            value = nu
    return float(value)


def hou_initial_swirl(
    grid: AxisymmetricGrid,
    *,
    amplitude: float = 12000.0,
    amplitude_scale: float = 1.0,
) -> FloatArray:
    """Return the E-29 initial swirl ``u_1(0, r, z)``.

    ``u_1(0,r,z) = A (1-r^2)^18 sin(2 pi z) / (1 + 12.5 sin^2(pi z))`` with the
    audited amplitude ``A = 12000`` scaled by ``amplitude_scale``.  The audited
    companion condition is ``omega_1(0) = 0``.
    """

    scale = float(amplitude) * float(amplitude_scale)
    if not math.isfinite(scale):
        raise ValueError("the initial swirl amplitude must be finite")
    radius, axial = grid.mesh()
    numerator = np.sin(2.0 * np.pi * axial)
    denominator = 1.0 + 12.5 * np.sin(np.pi * axial) ** 2
    return np.asarray(
        scale * (1.0 - radius**2) ** 18 * numerator / denominator,
        dtype=np.float64,
    )


def cartesian_vorticity(
    grid: AxisymmetricGrid,
    u1: npt.ArrayLike,
    omega1: npt.ArrayLike,
) -> tuple[FloatArray, FloatArray, FloatArray]:
    """Return the E-18b cylindrical vorticity components ``(w_r, w_theta, w_z)``."""

    swirl = grid.validate_field(u1, name="u1")
    vorticity = grid.validate_field(omega1, name="omega1")
    radius = grid.r[:, None]
    w_r = -radius * derivative_z(grid, swirl)
    w_theta = radius * vorticity
    w_z = 2.0 * swirl + radius * derivative_r(grid, swirl, even_at_axis=True)
    return w_r, w_theta, w_z


def _radial_weights(grid: AxisymmetricGrid) -> FloatArray:
    weights = grid.r.copy()
    weights[0] *= 0.5
    weights[-1] *= 0.5
    return weights


def _weighted_squared_norm(
    grid: AxisymmetricGrid,
    components: Sequence[FloatArray],
) -> float:
    total = np.zeros(grid.shape, dtype=np.float64)
    for component in components:
        total += component * component
    return float(
        grid.dr * grid.dz * np.sum(_radial_weights(grid)[:, None] * total)
    )


def kinetic_energy(grid: AxisymmetricGrid, state: ConstrainedState) -> float:
    """Return ``E = pi \\int (u^r)^2 + (u^theta)^2 + (u^z)^2 r dr dz`` (E-20a)."""

    radius = grid.r[:, None]
    return math.pi * _weighted_squared_norm(
        grid,
        (state.u_r, radius * state.u1, state.u_z),
    )


def enstrophy(grid: AxisymmetricGrid, state: ConstrainedState) -> float:
    """Return ``pi \\int |omega|^2 r dr dz``, the E-20 measure applied to E-18b."""

    return math.pi * _weighted_squared_norm(
        grid,
        cartesian_vorticity(grid, state.u1, state.omega1),
    )


def odd_symmetry_defect(grid: AxisymmetricGrid, field: npt.ArrayLike) -> float:
    """Return ``max |f(r, z_j) + f(r, z_{(nz-j) mod nz})|``.

    On the design grid ``z_j = j/n_z`` the reflection ``z -> 1 - z`` is the
    exact index map ``j -> (n_z - j) mod n_z``, so this measures the E-28 odd
    symmetry without interpolation.  The symmetry is monitored, never imposed.
    """

    values = grid.validate_field(field, name="field")
    reflected = values[:, (grid.nz - np.arange(grid.nz)) % grid.nz]
    return float(np.max(np.abs(values + reflected)))


def axis_parity_profile(
    grid: AxisymmetricGrid,
    field: npt.ArrayLike,
) -> FloatArray:
    """Return the one-sided second-order ``d_r f(0, z)`` estimate for every ``z``.

    This is the per-``z`` quantity whose supremum :func:`axis_parity_defect`
    reports; it is exactly the axis row of
    ``derivative_r(grid, field, even_at_axis=False)``.
    """

    values = grid.validate_field(field, name="field")
    return np.asarray(
        (-3.0 * values[0] + 4.0 * values[1] - values[2]) / (2.0 * grid.dr),
        dtype=np.float64,
    )


def axis_parity_defect(grid: AxisymmetricGrid, field: npt.ArrayLike) -> float:
    """Return ``max_z |D_r^{one-sided} f(0, z)|`` for an axis-even field.

    For a smooth even field the one-sided second-order estimate evaluates to
    ``-6 b dr^3 + O(dr^5)`` where ``b`` is the quartic Taylor coefficient, so
    the clean value is a discretization-order quantity of size ``O(dr^3)``, not
    a round-off quantity.  An odd component of size ``e`` would instead show up
    as ``O(e/dr)``, which is what this diagnostic detects (E-16c).
    """

    return float(np.max(np.abs(axis_parity_profile(grid, field))))


def relative_axis_parity(
    grid: AxisymmetricGrid,
    field: npt.ArrayLike,
) -> dict[str, float]:
    """Relativize the E-16c axis parity defect by the field's own gradient scale.

    The denominator is ``max |d_r f|`` over the whole grid, evaluated with the
    *same* one-sided axis stencil that produces the defect
    (``derivative_r(..., even_at_axis=False)``), so the axis row of the
    denominator is the defect itself and the ratio always lies in ``[0, 1]``.

    A clean axis-even field gives ``O(dr^3)`` over an ``O(1)`` radial gradient,
    i.e. a vanishing ratio under refinement.  An odd component of amplitude
    ``e`` contributes ``O(e/dr)`` to the numerator and only ``O(e/dr)`` to the
    denominator, so a broken field saturates the ratio at ``O(1)``.

    The returned keys are ``defect`` (absolute, identical to
    :func:`axis_parity_defect`), ``denominator``, ``relative`` and ``argmax_z``
    (the ``z`` location of the largest absolute defect).
    """

    values = grid.validate_field(field, name="field")
    profile = axis_parity_profile(grid, values)
    index = int(np.argmax(np.abs(profile)))
    defect = float(abs(profile[index]))
    denominator = float(
        np.max(np.abs(derivative_r(grid, values, even_at_axis=False)))
    )
    return {
        "defect": defect,
        "denominator": denominator,
        "relative": defect / max(denominator, _DENOMINATOR_FLOOR),
        "argmax_z": float(grid.z[index]),
    }


def relative_divergence(
    grid: AxisymmetricGrid,
    u_r: npt.ArrayLike,
    u_z: npt.ArrayLike,
) -> dict[str, float]:
    """Relativize the E-02 divergence residual by its own cancellation scale.

    The residual is :func:`~ns_certificate_lab.operators.divergence_physical`,
    and the denominator is the grid maximum of the pointwise term sum
    ``|d_r u^r| + |u^r/r| + |d_z u^z|`` built from
    :func:`~ns_certificate_lab.operators.divergence_terms`, i.e. from exactly
    the same three arrays whose sum is the residual (identical axis guard
    included).  This is the reciprocal of the TM-09 cancellation index
    ``kappa_res = sum_j |F_j| / (|sum_j F_j| + eps)``: a pointwise ratio near
    one means the residual is not a cancellation artefact at that point, while
    a ratio near ``1/kappa_res -> 0`` means the residual is the small
    difference of large terms and carries few significant digits.

    Returned keys: ``residual_max``, ``denominator``, ``relative``,
    ``argmax_r``/``argmax_z`` (location of the largest *absolute* residual),
    ``pointwise_ratio_max`` and ``pointwise_argmax_r``/``pointwise_argmax_z``
    (location of the largest *pointwise* ratio).
    """

    term_r, term_ratio, term_z = divergence_terms(grid, u_r, u_z)
    residual = np.abs(divergence_physical(grid, u_r, u_z))
    magnitude = np.abs(term_r) + np.abs(term_ratio) + np.abs(term_z)
    denominator = float(np.max(magnitude))
    residual_row, residual_column = divmod(int(np.argmax(residual)), grid.nz)
    pointwise = residual / (magnitude + _DENOMINATOR_FLOOR)
    pointwise_row, pointwise_column = divmod(int(np.argmax(pointwise)), grid.nz)
    return {
        "residual_max": float(residual[residual_row, residual_column]),
        "denominator": denominator,
        "relative": float(
            residual[residual_row, residual_column]
            / max(denominator, _DENOMINATOR_FLOOR)
        ),
        "argmax_r": float(grid.r[residual_row]),
        "argmax_z": float(grid.z[residual_column]),
        "pointwise_ratio_max": float(pointwise[pointwise_row, pointwise_column]),
        "pointwise_argmax_r": float(grid.r[pointwise_row]),
        "pointwise_argmax_z": float(grid.z[pointwise_column]),
    }


def compute_diagnostics(
    grid: AxisymmetricGrid,
    state: ConstrainedState,
    *,
    time: float,
    dt: float,
    viscosity: float,
    step: int,
    reference_vorticity_max: float | None = None,
) -> dict[str, float]:
    """Return the design section 5 scalar diagnostics for one state."""

    w_r, w_theta, w_z = cartesian_vorticity(grid, state.u1, state.omega1)
    vorticity_magnitude = np.sqrt(w_r * w_r + w_theta * w_theta + w_z * w_z)
    max_vorticity = float(np.max(vorticity_magnitude))
    reference = (
        max_vorticity
        if reference_vorticity_max is None
        else float(reference_vorticity_max)
    )
    amplification = (
        max_vorticity / reference if reference > 0.0 else float("nan")
    )
    flat_index = int(np.argmax(state.u1))
    row, column = divmod(flat_index, grid.nz)
    vorticity_row, vorticity_column = divmod(
        int(np.argmax(vorticity_magnitude)), grid.nz
    )
    max_u_r = float(np.max(np.abs(state.u_r)))
    max_u_z = float(np.max(np.abs(state.u_z)))
    circulation = grid.r[:, None] ** 2 * state.u1
    divergence = relative_divergence(grid, state.u_r, state.u_z)
    parity_u1 = relative_axis_parity(grid, state.u1)
    parity_omega1 = relative_axis_parity(grid, state.omega1)
    return {
        "step": float(step),
        "time": float(time),
        "dt": float(dt),
        "viscosity": float(viscosity),
        "energy": kinetic_energy(grid, state),
        "enstrophy": enstrophy(grid, state),
        "max_abs_u1": float(np.max(np.abs(state.u1))),
        "max_abs_omega1": float(np.max(np.abs(state.omega1))),
        "max_abs_psi1": float(np.max(np.abs(state.psi1))),
        "max_abs_u_r": max_u_r,
        "max_abs_u_z": max_u_z,
        "max_cartesian_vorticity": max_vorticity,
        "amplification": float(amplification),
        "argmax_u1_r": float(grid.r[row]),
        "argmax_u1_z": float(grid.z[column]),
        "argmax_u1_value": float(state.u1[row, column]),
        "circulation_max": float(np.max(np.abs(circulation))),
        "divergence_residual_max": divergence["residual_max"],
        "axis_parity_defect": max(
            parity_u1["defect"],
            parity_omega1["defect"],
            axis_parity_defect(grid, state.psi1),
        ),
        "odd_symmetry_defect": max(
            odd_symmetry_defect(grid, state.u1),
            odd_symmetry_defect(grid, state.omega1),
            odd_symmetry_defect(grid, state.psi1),
        ),
        "wall_u1_max_abs": float(np.max(np.abs(state.u1[-1]))),
        # ``dt`` was selected from the *previous* state (see the module
        # docstring); this is the post-step effective CFL of that step.
        "advective_cfl": float(
            dt * max(max_u_r / grid.dr, max_u_z / grid.dz)
        ),
        "viscous_cfl": float(
            4.0 * viscosity * dt / min(grid.dr**2, grid.dz**2)
        ),
        # --- relativized constraint diagnostics (TM-09), recorded not gated ---
        "divergence_relative_denominator": divergence["denominator"],
        "divergence_residual_relative": divergence["relative"],
        "divergence_residual_argmax_r": divergence["argmax_r"],
        "divergence_residual_argmax_z": divergence["argmax_z"],
        "divergence_pointwise_ratio_max": divergence["pointwise_ratio_max"],
        "divergence_pointwise_ratio_argmax_r": divergence["pointwise_argmax_r"],
        "divergence_pointwise_ratio_argmax_z": divergence["pointwise_argmax_z"],
        "axis_parity_defect_u1": parity_u1["defect"],
        "axis_parity_defect_omega1": parity_omega1["defect"],
        "axis_parity_relative_u1": parity_u1["relative"],
        "axis_parity_relative_omega1": parity_omega1["relative"],
        "axis_parity_relative_denominator_u1": parity_u1["denominator"],
        "axis_parity_relative_denominator_omega1": parity_omega1["denominator"],
        "axis_parity_argmax_z_u1": parity_u1["argmax_z"],
        "axis_parity_argmax_z_omega1": parity_omega1["argmax_z"],
        "argmax_cartesian_vorticity_r": float(grid.r[vorticity_row]),
        "argmax_cartesian_vorticity_z": float(grid.z[vorticity_column]),
    }


DIAGNOSTIC_FIELDS: tuple[str, ...] = (
    "step",
    "time",
    "dt",
    "viscosity",
    "energy",
    "enstrophy",
    "max_abs_u1",
    "max_abs_omega1",
    "max_abs_psi1",
    "max_abs_u_r",
    "max_abs_u_z",
    "max_cartesian_vorticity",
    "amplification",
    "argmax_u1_r",
    "argmax_u1_z",
    "argmax_u1_value",
    "circulation_max",
    "divergence_residual_max",
    "axis_parity_defect",
    "odd_symmetry_defect",
    "wall_u1_max_abs",
    "advective_cfl",
    "viscous_cfl",
    "divergence_relative_denominator",
    "divergence_residual_relative",
    "divergence_residual_argmax_r",
    "divergence_residual_argmax_z",
    "divergence_pointwise_ratio_max",
    "divergence_pointwise_ratio_argmax_r",
    "divergence_pointwise_ratio_argmax_z",
    "axis_parity_defect_u1",
    "axis_parity_defect_omega1",
    "axis_parity_relative_u1",
    "axis_parity_relative_omega1",
    "axis_parity_relative_denominator_u1",
    "axis_parity_relative_denominator_omega1",
    "axis_parity_argmax_z_u1",
    "axis_parity_argmax_z_omega1",
    "argmax_cartesian_vorticity_r",
    "argmax_cartesian_vorticity_z",
)

# The relativized entries of :func:`compute_diagnostics`; every one of them is
# recorded only and no acceptance gate reads them.
RELATIVE_DIAGNOSTIC_FIELDS: tuple[str, ...] = (
    "divergence_relative_denominator",
    "divergence_residual_relative",
    "divergence_residual_argmax_r",
    "divergence_residual_argmax_z",
    "divergence_pointwise_ratio_max",
    "divergence_pointwise_ratio_argmax_r",
    "divergence_pointwise_ratio_argmax_z",
    "axis_parity_defect_u1",
    "axis_parity_defect_omega1",
    "axis_parity_relative_u1",
    "axis_parity_relative_omega1",
    "axis_parity_relative_denominator_u1",
    "axis_parity_relative_denominator_omega1",
    "axis_parity_argmax_z_u1",
    "axis_parity_argmax_z_omega1",
)


@dataclass(frozen=True)
class IntegrationResult:
    """Final state, diagnostic history and step bookkeeping of one run."""

    grid: AxisymmetricGrid
    state: ConstrainedState
    time: float
    step_count: int
    history: tuple[dict[str, float], ...]
    snapshot_times: tuple[float, ...]
    viscosity_switch_times: tuple[float, ...]
    reference_vorticity_max: float
    completed: bool


def _step_targets(
    *,
    initial_time: float,
    t_final: float,
    schedule: tuple[tuple[float, float], ...],
    snapshot_times: Sequence[float],
) -> tuple[float, ...]:
    values = {float(t_final)}
    for switch_time, _ in schedule:
        if initial_time + _TIME_TOLERANCE < switch_time < t_final - _TIME_TOLERANCE:
            values.add(float(switch_time))
    for raw in snapshot_times:
        moment = float(raw)
        if not math.isfinite(moment):
            raise ValueError("snapshot times must be finite")
        if moment < initial_time - _TIME_TOLERANCE or moment > t_final + _TIME_TOLERANCE:
            raise ValueError("snapshot times must lie in [initial_time, t_final]")
        if moment > initial_time + _TIME_TOLERANCE:
            values.add(min(moment, float(t_final)))
    return tuple(sorted(values))


def integrate(
    grid: AxisymmetricGrid,
    *,
    u1: npt.ArrayLike,
    omega1: npt.ArrayLike,
    t_final: float,
    viscosity_schedule: Sequence[Sequence[float]],
    initial_time: float = 0.0,
    cfl_coefficient: float = 0.1,
    fixed_time_step: float | None = None,
    max_time_step: float | None = None,
    max_steps: int = 1_000_000,
    snapshot_times: Sequence[float] = (),
    forcing_u1: Forcing = None,
    forcing_omega1: Forcing = None,
    fault: Fault | None = None,
    diagnostic_stride: int = 1,
    on_snapshot: Callable[[float, ConstrainedState, dict[str, float]], None] | None = None,
    reference_vorticity_max: float | None = None,
) -> IntegrationResult:
    """Integrate E-11/E-12 from ``initial_time`` to ``t_final``.

    ``fixed_time_step`` selects the uniform-step mode used by convergence
    tests; otherwise the adaptive rule of :func:`adaptive_time_step` applies and
    steps are clipped so that viscosity switch times, snapshot times and
    ``t_final`` are hit exactly.
    """

    _check_fault(fault)
    schedule = normalize_viscosity_schedule(viscosity_schedule)
    start = float(initial_time)
    stop = float(t_final)
    if not (math.isfinite(start) and math.isfinite(stop)) or stop <= start:
        raise ValueError("t_final must be finite and greater than initial_time")
    if isinstance(max_steps, bool) or not isinstance(max_steps, int) or max_steps < 1:
        raise ValueError("max_steps must be a positive integer")
    if (
        isinstance(diagnostic_stride, bool)
        or not isinstance(diagnostic_stride, int)
        or diagnostic_stride < 1
    ):
        raise ValueError("diagnostic_stride must be a positive integer")

    targets = _step_targets(
        initial_time=start,
        t_final=stop,
        schedule=schedule,
        snapshot_times=snapshot_times,
    )
    requested_snapshots = tuple(
        sorted(
            {
                float(value)
                for value in snapshot_times
                if math.isfinite(float(value))
            }
        )
    )

    uniform_dt: float | None = None
    if fixed_time_step is not None:
        requested = float(fixed_time_step)
        if not math.isfinite(requested) or requested <= 0.0:
            raise ValueError("fixed_time_step must be positive and finite")
        step_count = max(1, math.ceil((stop - start) / requested))
        uniform_dt = (stop - start) / step_count
        for target in targets:
            offset = (target - start) / uniform_dt
            if abs(offset - round(offset)) > 1.0e-9 * max(1.0, abs(offset)):
                raise ValueError(
                    "fixed_time_step mode requires switch and snapshot times on "
                    "step boundaries"
                )

    state = constrain_state(grid, u1, omega1, fault=fault)
    reference = (
        float(reference_vorticity_max)
        if reference_vorticity_max is not None
        else float(
            np.max(
                np.sqrt(
                    sum(
                        component * component
                        for component in cartesian_vorticity(
                            grid, state.u1, state.omega1
                        )
                    )
                )
            )
        )
    )
    time = start
    history: list[dict[str, float]] = []
    recorded = compute_diagnostics(
        grid,
        state,
        time=time,
        dt=0.0,
        viscosity=viscosity_at(schedule, time),
        step=0,
        reference_vorticity_max=reference,
    )
    history.append(recorded)
    if on_snapshot is not None and any(
        abs(time - value) <= _TIME_TOLERANCE for value in requested_snapshots
    ):
        on_snapshot(time, state, recorded)

    switch_times: list[float] = []
    step_index = 0
    target_index = 0
    completed = False
    while target_index < len(targets):
        target = targets[target_index]
        while time < target - _TIME_TOLERANCE:
            if step_index >= max_steps:
                break
            nu = viscosity_at(schedule, time)
            if uniform_dt is not None:
                dt = uniform_dt
            else:
                dt = adaptive_time_step(
                    grid,
                    state,
                    viscosity=nu,
                    cfl_coefficient=cfl_coefficient,
                    max_time_step=max_time_step,
                )
            landed = False
            if dt >= target - time - _TIME_TOLERANCE:
                dt = target - time
                landed = True
            state = heun_step(
                grid,
                state,
                dt=dt,
                time=time,
                viscosity=nu,
                forcing_u1=forcing_u1,
                forcing_omega1=forcing_omega1,
                fault=fault,
            )
            time = target if landed else time + dt
            step_index += 1
            if not (
                np.all(np.isfinite(state.u1)) and np.all(np.isfinite(state.omega1))
            ):
                raise FloatingPointError("nonlinear cylinder state became non-finite")
            at_target = landed
            if step_index % diagnostic_stride == 0 or at_target:
                history.append(
                    compute_diagnostics(
                        grid,
                        state,
                        time=time,
                        dt=dt,
                        viscosity=nu,
                        step=step_index,
                        reference_vorticity_max=reference,
                    )
                )
        if time < target - _TIME_TOLERANCE:
            break
        if any(abs(target - value) <= _TIME_TOLERANCE for value in requested_snapshots):
            if on_snapshot is not None:
                on_snapshot(target, state, history[-1])
        if any(abs(target - switch) <= _TIME_TOLERANCE for switch, _ in schedule[1:]):
            switch_times.append(float(target))
        target_index += 1
    else:
        completed = True

    return IntegrationResult(
        grid=grid,
        state=state,
        time=time,
        step_count=step_index,
        history=tuple(history),
        snapshot_times=requested_snapshots,
        viscosity_switch_times=tuple(switch_times),
        reference_vorticity_max=reference,
        completed=completed,
    )


def checkpoint_description(
    *,
    physical_time: float,
    viscosity: float,
) -> dict[str, Any]:
    """Return the candidate v2 description block for a solver checkpoint."""

    return {
        "representation": (
            "transformed axisymmetric state (u1, omega1, psi1) on a uniform "
            "finite-cylinder grid with periodic z"
        ),
        "coordinate_system": "axisymmetric cylindrical half-plane (r, z)",
        "units": {
            "r": "dimensionless length",
            "z": "dimensionless length",
            "u1": "dimensionless inverse time (u^theta / r)",
            "omega1": "dimensionless inverse length inverse time (omega^theta / r)",
            "psi1": "dimensionless length inverse time (psi^theta / r)",
        },
        "normalization": (
            "Hou finite-cylinder normalization: r in [0,1], z period 1, "
            "u1 = u^theta/r, omega1 = omega^theta/r, psi1 = psi^theta/r"
        ),
        "physical_time": float(physical_time),
        "viscosity": float(viscosity),
        "basis_convention": (
            "nodal float64 values on the uniform (r, z) tensor grid, r-major, "
            "z endpoint omitted"
        ),
    }


def save_checkpoint(
    path: str | Path,
    *,
    grid: AxisymmetricGrid,
    state: ConstrainedState,
    time: float,
    viscosity: float,
    seed: int,
    config: Mapping[str, Any],
    provenance: Mapping[str, Any] | None = None,
    metadata: Mapping[str, Any] | None = None,
) -> CandidatePaths:
    """Write a candidate schema v2 checkpoint of ``(u1, omega1, psi1)``."""

    extra = dict(metadata or {})
    extra.setdefault("solver", "ns_certificate_lab.nonlinear_cylinder")
    extra.setdefault(
        "interpretation",
        "floating-point candidate snapshot; not a proof and not evidence of "
        "singularity formation",
    )
    extra.setdefault("physical_time", float(time))
    extra.setdefault("viscosity", float(viscosity))
    return save_candidate(
        path,
        grid=grid,
        fields={
            "u1": state.u1,
            "omega1": state.omega1,
            "psi1": state.psi1,
        },
        config=config,
        seed=seed,
        description=checkpoint_description(
            physical_time=float(time),
            viscosity=float(viscosity),
        ),
        metadata=extra,
        provenance=provenance,
    )


@dataclass(frozen=True)
class Checkpoint:
    """A restored checkpoint ready to resume."""

    grid: AxisymmetricGrid
    state: ConstrainedState
    time: float
    viscosity: float
    config: dict[str, Any]
    metadata: dict[str, Any]
    seed: int


def load_checkpoint(path: str | Path, *, fault: Fault | None = None) -> Checkpoint:
    """Load and re-constrain a checkpoint written by :func:`save_checkpoint`."""

    artifact = load_candidate(path)
    if artifact.description is None:
        raise ValueError("nonlinear cylinder checkpoints require a v2 description")
    if set(artifact.fields) != {"u1", "omega1", "psi1"}:
        raise ValueError("checkpoint must store exactly u1, omega1 and psi1")
    state = constrain_state(
        artifact.grid,
        artifact.fields["u1"],
        artifact.fields["omega1"],
        fault=fault,
    )
    return Checkpoint(
        grid=artifact.grid,
        state=state,
        time=float(artifact.description.physical_time),
        viscosity=float(artifact.description.viscosity),
        config=dict(artifact.config),
        metadata=dict(artifact.metadata),
        seed=int(artifact.seed),
    )


def resume(
    path: str | Path,
    *,
    t_final: float,
    viscosity_schedule: Sequence[Sequence[float]],
    **options: Any,
) -> IntegrationResult:
    """Resume :func:`integrate` from a saved checkpoint."""

    checkpoint = load_checkpoint(path, fault=options.get("fault"))
    return integrate(
        checkpoint.grid,
        u1=checkpoint.state.u1,
        omega1=checkpoint.state.omega1,
        t_final=t_final,
        viscosity_schedule=viscosity_schedule,
        initial_time=checkpoint.time,
        **options,
    )
