r"""Kinematic and far-field checks for a Zeno packet-relay candidate.

This module studies one deliberately narrow question.  Can a hierarchy of
spatially disjoint, Navier--Stokes-scaled packets evade the energy and total
dissipation obstructions while accumulating critical ``L^3`` mass?

For a fixed divergence-free template ``W`` and dyadic wavenumbers
``lambda_j = base**j``, the kinematic packet is

.. math::

   w_j(x) = \lambda_j W(\lambda_j(x-x_j)).

If the supports are disjoint, then its packet energy is proportional to
``lambda_j**-1`` while its ``L^3`` mass is independent of ``j``.  A stack of
``J+1`` packets therefore has bounded energy, enstrophy of order
``lambda_J``, and ``L^3`` mass of order ``J``.  This is the finite-low-frequency
floor that the historical positive-slope shell classifier did not model.

A compactly supported packet is not exactly band limited.  Consequently, the
packet sums and the modeled Littlewood--Paley shell sums computed here are two
separate kinematic checks.  Identifying them requires spectral-leakage bounds;
this module does not assume that bridge.

The module also evaluates the leading far-field pressure Hessian generated by
one packet.  If

.. math::

   M_{ij}=\int u_i u_j\,dx,

then outside the transmitter support

.. math::

   p(x)=M_{ij}\,\partial_i\partial_j(4\pi|x|)^{-1}+O(|x|^{-4}),

so ``Hess(p)`` is the fourth derivative of the Newtonian kernel and decays as
``distance**-5``.  The sign test here only establishes that a favourable
pressure-strain orientation is algebraically possible.  It does not establish
that Navier--Stokes dynamics creates, transports, or preserves the packet
stack.

Scientific status: **FORMAL ANSATZ / AUDIT REQUIRED**.  No function in this
module constructs a Navier--Stokes solution or proves blow-up.
"""

from __future__ import annotations

from dataclasses import dataclass
import math

import numpy as np
import numpy.typing as npt

FloatArray = npt.NDArray[np.float64]

__all__ = [
    "CriticalStaircaseMetrics",
    "FiniteFloorShellVerdict",
    "MovingFrontLaw",
    "classify_finite_floor_shell_exponents",
    "critical_staircase_metrics",
    "finite_floor_shell_sums",
    "gaussian_vortex_moment",
    "pressure_hessian_quadrupole",
    "normalized_pressure_stretch",
    "zeno_scaling_exponents",
]


def _finite(value: float, *, name: str) -> float:
    converted = float(value)
    if not math.isfinite(converted):
        raise ValueError(f"{name} must be finite")
    return converted


@dataclass(frozen=True)
class CriticalStaircaseMetrics:
    """Exact finite sums for ``E_j = energy_constant / lambda_j``.

    ``critical_l3_cubed`` uses the additional kinematic assumption that the
    physical packet supports are disjoint.  ``critical_besov`` is instead the
    value of the *modeled* shell sum
    ``sum_j lambda_j**(1/2) E_j**(1/2)``.  The two values cannot both be read as
    exact properties of one compact, exactly band-limited template.
    """

    max_level: int
    base: float
    bandwidth: float
    shell_count: int
    energy: float
    enstrophy: float
    critical_besov: float
    critical_l3_cubed: float
    vorticity_linf_scale: float
    nonlinear_l2_scale: float
    pressure_gradient_l2_scale: float

    def as_dict(self) -> dict[str, int | float]:
        return {
            "max_level": self.max_level,
            "base": self.base,
            "bandwidth": self.bandwidth,
            "shell_count": self.shell_count,
            "energy": self.energy,
            "enstrophy": self.enstrophy,
            "critical_besov": self.critical_besov,
            "critical_l3_cubed": self.critical_l3_cubed,
            "vorticity_linf_scale": self.vorticity_linf_scale,
            "nonlinear_l2_scale": self.nonlinear_l2_scale,
            "pressure_gradient_l2_scale": self.pressure_gradient_l2_scale,
        }


def critical_staircase_metrics(
    max_level: int,
    *,
    base: float = 2.0,
    energy_constant: float = 1.0,
    packet_l3_cubed: float = 1.0,
) -> CriticalStaircaseMetrics:
    """Return the finite-floor metrics for levels ``0, ..., max_level``."""

    if isinstance(max_level, bool) or not isinstance(max_level, int) or max_level < 0:
        raise ValueError("max_level must be a nonnegative integer")
    base = _finite(base, name="base")
    energy_constant = _finite(energy_constant, name="energy_constant")
    packet_l3_cubed = _finite(packet_l3_cubed, name="packet_l3_cubed")
    if base <= 1.0:
        raise ValueError("base must exceed one")
    if energy_constant <= 0.0 or packet_l3_cubed <= 0.0:
        raise ValueError("packet constants must be positive")

    maximum_log = max_level * math.log(base)
    if 2.0 * maximum_log > math.log(np.finfo(np.float64).max):
        raise ValueError("max_level and base would overflow reported metrics")
    levels = np.arange(max_level + 1, dtype=np.float64)
    wavenumbers = base**levels
    shell_energy = energy_constant / wavenumbers
    bandwidth = float(wavenumbers[-1])
    shell_count = max_level + 1
    energy = float(np.sum(shell_energy))
    enstrophy = float(energy_constant * np.sum(wavenumbers))
    critical_besov = float(np.sum(np.sqrt(wavenumbers * shell_energy)))
    critical_l3_cubed = packet_l3_cubed * shell_count

    # A critical packet has velocity amplitude O(lambda), width O(lambda^-1),
    # hence vorticity O(lambda^2).  Both (u.grad)u and grad(p) have amplitude
    # O(lambda^3) and L2 norm O(lambda^(3/2)).
    return CriticalStaircaseMetrics(
        max_level=max_level,
        base=base,
        bandwidth=bandwidth,
        shell_count=shell_count,
        energy=energy,
        enstrophy=enstrophy,
        critical_besov=critical_besov,
        critical_l3_cubed=critical_l3_cubed,
        vorticity_linf_scale=bandwidth**2,
        nonlinear_l2_scale=bandwidth**1.5,
        pressure_gradient_l2_scale=bandwidth**1.5,
    )


def finite_floor_shell_sums(
    max_level: int,
    *,
    spectral_slope: float,
    peak_energy: float,
    base: float = 2.0,
) -> tuple[float, float, float]:
    r"""Compute the *finite* torus shell sums with lowest wavenumber one.

    The modeled spectrum is

    .. math:: E_j=A(\lambda_j/N)^\beta,\quad 0\le j\le J,\quad N=b^J.

    Returns total energy, enstrophy, and the critical
    ``B^{1/2}_{2,1}`` shell sum.  No infinite low-frequency tail is inserted.
    """

    if isinstance(max_level, bool) or not isinstance(max_level, int) or max_level < 0:
        raise ValueError("max_level must be a nonnegative integer")
    beta = _finite(spectral_slope, name="spectral_slope")
    amplitude = _finite(peak_energy, name="peak_energy")
    base = _finite(base, name="base")
    if amplitude < 0.0:
        raise ValueError("peak_energy must be nonnegative")
    if base <= 1.0:
        raise ValueError("base must exceed one")

    maximum_log = max_level * math.log(base)
    if maximum_log > math.log(np.finfo(np.float64).max):
        raise ValueError("max_level and base would overflow the bandwidth")
    levels = np.arange(max_level + 1, dtype=np.float64)
    wavenumbers = base**levels
    front = float(wavenumbers[-1])
    with np.errstate(over="ignore", invalid="ignore", under="ignore"):
        energies = amplitude * (wavenumbers / front) ** beta
        values = (
            float(np.sum(energies)),
            float(np.sum(wavenumbers**2 * energies)),
            float(np.sum(np.sqrt(wavenumbers * energies))),
        )
    if not all(math.isfinite(value) for value in values):
        raise ValueError("shell parameters overflow the requested finite sums")
    return values


@dataclass(frozen=True)
class FiniteFloorShellVerdict:
    """Piecewise asymptotic conditions with a fixed lowest torus shell."""

    bandwidth_exponent: float
    peak_energy_exponent: float
    spectral_slope: float
    energy_bounded: bool
    dissipation_integrable: bool
    critical_upper_bound_not_uniform: bool
    bandwidth_diverges: bool
    logarithmic_critical_boundary: bool

    @property
    def kinematically_admissible(self) -> bool:
        return (
            self.bandwidth_diverges
            and self.energy_bounded
            and self.dissipation_integrable
            and self.critical_upper_bound_not_uniform
        )

    def as_dict(self) -> dict[str, bool | float]:
        return {
            "bandwidth_exponent": self.bandwidth_exponent,
            "peak_energy_exponent": self.peak_energy_exponent,
            "spectral_slope": self.spectral_slope,
            "energy_bounded": self.energy_bounded,
            "dissipation_integrable": self.dissipation_integrable,
            "critical_upper_bound_not_uniform": (
                self.critical_upper_bound_not_uniform
            ),
            "bandwidth_diverges": self.bandwidth_diverges,
            "logarithmic_critical_boundary": self.logarithmic_critical_boundary,
            "kinematically_admissible": self.kinematically_admissible,
        }


def classify_finite_floor_shell_exponents(
    bandwidth_exponent: float,
    peak_energy_exponent: float,
    spectral_slope: float,
) -> FiniteFloorShellVerdict:
    r"""Classify the finite-floor power law, retaining logarithmic endpoints.

    Let ``N=tau^-gamma``, ``A=tau^sigma`` and use the finite shell range
    ``1 <= lambda_j <= N``.  The piecewise sums are:

    * energy: ``A`` for ``beta>0``, ``A log N`` for ``beta=0``, and
      ``A N^-beta`` for ``beta<0``;
    * enstrophy: ``A N^2`` for ``beta>-2`` (with a logarithm at ``-2``),
      and ``A N^-beta`` for ``beta<-2``;
    * critical Besov bound: ``A^(1/2) N^(1/2)`` for ``beta>-1``, with
      an extra ``log N`` at ``beta=-1``, and ``A^(1/2)N^(-beta/2)``
      for ``beta<-1``.

    ``critical_upper_bound_not_uniform`` means only that this standard upper
    bound does not stay uniform.  It is not a proof that ``L^3`` diverges.
    """

    gamma = _finite(bandwidth_exponent, name="bandwidth_exponent")
    sigma = _finite(peak_energy_exponent, name="peak_energy_exponent")
    beta = _finite(spectral_slope, name="spectral_slope")

    if beta > 0.0:
        energy_bounded = sigma >= 0.0
    elif beta < 0.0:
        energy_bounded = sigma + gamma * beta >= 0.0
    else:
        # A log N is unbounded at sigma=0 but any positive power of tau wins.
        energy_bounded = sigma > 0.0

    if beta >= -2.0:
        dissipation_integrable = sigma - 2.0 * gamma > -1.0
    else:
        dissipation_integrable = sigma + gamma * beta > -1.0

    if beta > -1.0:
        critical_not_uniform = sigma < gamma
        logarithmic_boundary = False
    elif beta < -1.0:
        critical_not_uniform = sigma + gamma * beta < 0.0
        logarithmic_boundary = False
    else:
        critical_not_uniform = sigma <= gamma
        logarithmic_boundary = sigma == gamma

    return FiniteFloorShellVerdict(
        bandwidth_exponent=gamma,
        peak_energy_exponent=sigma,
        spectral_slope=beta,
        energy_bounded=energy_bounded,
        dissipation_integrable=dissipation_integrable,
        critical_upper_bound_not_uniform=critical_not_uniform,
        bandwidth_diverges=gamma > 0.0,
        logarithmic_critical_boundary=logarithmic_boundary,
    )


def pressure_hessian_quadrupole(
    moment: npt.ArrayLike,
    displacement: npt.ArrayLike,
) -> FloatArray:
    r"""Leading far-field pressure Hessian of a localized transmitter.

    The returned matrix is
    ``M_ij partial_a partial_b partial_i partial_j (4 pi |x|)^-1``.
    Terms involving higher source moments are deliberately not estimated here.
    """

    matrix = np.asarray(moment, dtype=np.float64)
    vector = np.asarray(displacement, dtype=np.float64)
    if matrix.shape != (3, 3) or vector.shape != (3,):
        raise ValueError("moment must be 3x3 and displacement must have length three")
    if not np.all(np.isfinite(matrix)) or not np.all(np.isfinite(vector)):
        raise ValueError("moment and displacement must be finite")
    if not np.allclose(matrix, matrix.T, rtol=0.0, atol=1.0e-12):
        raise ValueError("moment must be symmetric")
    matrix = 0.5 * (matrix + matrix.T)
    scale = max(1.0, float(np.linalg.norm(matrix, ord=2)))
    if float(np.min(np.linalg.eigvalsh(matrix))) < -1.0e-12 * scale:
        raise ValueError("an energy moment must be positive semidefinite")
    distance = float(np.linalg.norm(vector))
    if distance <= 0.0:
        raise ValueError("displacement must be nonzero")
    n = vector / distance
    delta = np.eye(3, dtype=np.float64)
    hessian = np.zeros((3, 3), dtype=np.float64)

    for a in range(3):
        for b in range(3):
            for i in range(3):
                for j in range(3):
                    tensor = 105.0 * n[a] * n[b] * n[i] * n[j]
                    tensor -= 15.0 * (
                        delta[a, b] * n[i] * n[j]
                        + delta[a, i] * n[b] * n[j]
                        + delta[a, j] * n[b] * n[i]
                        + delta[b, i] * n[a] * n[j]
                        + delta[b, j] * n[a] * n[i]
                        + delta[i, j] * n[a] * n[b]
                    )
                    tensor += 3.0 * (
                        delta[a, b] * delta[i, j]
                        + delta[a, i] * delta[b, j]
                        + delta[a, j] * delta[b, i]
                    )
                    hessian[a, b] += matrix[i, j] * tensor
    hessian /= 4.0 * math.pi * distance**5
    return hessian


def gaussian_vortex_moment(axis: npt.ArrayLike) -> FloatArray:
    r"""Return the unit-trace moment of an explicit solenoidal Schwartz field.

    For a unit vector ``a``, the field

    ``W_a(x) = (a cross x) exp(-|x|^2 / 2)``

    is divergence free and Schwartz.  Rotational symmetry gives
    ``integral W_a tensor W_a = c (I - a tensor a)`` for ``c>0``.  The returned
    matrix divides out its trace, because normalized pressure stretch is
    insensitive to ``c``.
    """

    vector = np.asarray(axis, dtype=np.float64)
    if vector.shape != (3,) or not np.all(np.isfinite(vector)):
        raise ValueError("axis must be a finite length-three vector")
    norm = float(np.linalg.norm(vector))
    if norm <= 0.0:
        raise ValueError("axis must be nonzero")
    unit = vector / norm
    return 0.5 * (np.eye(3, dtype=np.float64) - np.outer(unit, unit))


def normalized_pressure_stretch(
    moment: npt.ArrayLike,
    displacement: npt.ArrayLike,
    direction: npt.ArrayLike,
) -> float:
    r"""Return ``-4 pi d^5 e.Hess(p).e / trace(M)``.

    A positive value means the leading pressure term ``-Hess(p)`` accelerates
    strain in direction ``e``.  Normalization removes transmitter energy and
    separation scale.
    """

    matrix = np.asarray(moment, dtype=np.float64)
    vector = np.asarray(displacement, dtype=np.float64)
    axis = np.asarray(direction, dtype=np.float64)
    if axis.shape != (3,) or not np.all(np.isfinite(axis)):
        raise ValueError("direction must be a finite length-three vector")
    norm = float(np.linalg.norm(axis))
    if norm <= 0.0:
        raise ValueError("direction must be nonzero")
    trace = float(np.trace(matrix))
    if trace <= 0.0:
        raise ValueError("moment must have positive trace")
    distance = float(np.linalg.norm(vector))
    unit_axis = axis / norm
    hessian = pressure_hessian_quadrupole(matrix, vector)
    return float(
        -4.0
        * math.pi
        * distance**5
        * np.dot(unit_axis, hessian @ unit_axis)
        / trace
    )


@dataclass(frozen=True)
class MovingFrontLaw:
    r"""Solution of ``dN/dt = coefficient * N^3``.

    Dividing a scale-local net flux ``O(N)`` by the new-shell energy ``O(N^-1)``
    gives a shell activation rate ``O(N^2)``; converting shell index to
    bandwidth gives this cubic front law.  A positive coefficient produces the
    parabolic front ``N ~ (T-t)^-1/2``.
    """

    initial_bandwidth: float
    coefficient: float
    initial_time: float = 0.0

    def __post_init__(self) -> None:
        initial_bandwidth = _finite(
            self.initial_bandwidth, name="initial_bandwidth"
        )
        coefficient = _finite(self.coefficient, name="coefficient")
        initial_time = _finite(self.initial_time, name="initial_time")
        if initial_bandwidth <= 0.0:
            raise ValueError("initial_bandwidth must be positive")
        if coefficient <= 0.0:
            raise ValueError("coefficient must be positive")
        object.__setattr__(self, "initial_bandwidth", initial_bandwidth)
        object.__setattr__(self, "coefficient", coefficient)
        object.__setattr__(self, "initial_time", initial_time)

    @property
    def blowup_time(self) -> float:
        return self.initial_time + 1.0 / (
            2.0 * self.coefficient * self.initial_bandwidth**2
        )

    def bandwidth(self, time: float) -> float:
        time = _finite(time, name="time")
        denominator = self.initial_bandwidth ** (-2.0) - 2.0 * self.coefficient * (
            time - self.initial_time
        )
        if denominator <= 0.0:
            raise ValueError("time must precede the formal front blow-up time")
        return denominator ** (-0.5)


def zeno_scaling_exponents(gamma: float) -> dict[str, float | str]:
    r"""Scaling table for the critical packet staircase ``N=tau^-gamma``."""

    gamma = _finite(gamma, name="gamma")
    if gamma <= 0.0:
        raise ValueError("gamma must be positive")
    return {
        "energy": 0.0,
        "enstrophy": -gamma,
        "global_l3_cubed": "log(1/tau)",
        "vorticity_linf": -2.0 * gamma,
        "dissipation_rate": -gamma,
        "nonlinear_l2": -1.5 * gamma,
        "pressure_gradient_l2": -1.5 * gamma,
        "physical_time_remaining": 1.0,
        "fourier_bandwidth": -gamma,
        "finite_total_dissipation_requires": "gamma < 1",
        "bkm_divergence_requires": "gamma >= 1/2",
    }
